Template - Inserir opacidade das sombras das imagens
EdisonMatos/Dev-Template pull request #251
Opened 2024-11-05 15:17 UTC by BiellSouza

2024-11-05 15:37 UTC, BiellSouza commented
Testado

2024-11-07 12:10 UTC, EdisonMatos requested changes
- Na Hero, colocar cor: bgSectionDark, com 100%
- No about e steps. colocar Black com 50%

2024-11-07 12:31 UTC, BiellSouza commented
> * Na Hero, colocar cor: bgSectionDark, com 100%
> * No about e steps. colocar Black com 50%

Atualizado!

2024-11-07 12:31 UTC, BiellSouza commented
Atualizado - Testado!

2024-11-08 18:00 UTC, merged